### PR TITLE
Autoconf update

### PR DESCRIPTION
**Pull request by JamesWrigley**
Hi!
I think it's finished now, I tested this on 32bit, 64bit, and ARM 32bit and Nitrogen built successfully in all cases.

Thanks,
JamesNZ

### CODE REVIEW

**Comment by daf** [comment]
@JamesWrigley, just tested this locally - I still needed 30b50d1e3d77966cd29e27c12dbe8f12eff2175d applied which your commits removed, otherwise I get #12 again.  Thoughts?

Also, autoreconf changed a bunch of boilerplate stuff - should that be tracked by this repo (aka, should I update and commit it), or should many of those files be put in .gitignore?

**Comment by JamesWrigley** [comment]
@daf, good catch, I've reapplied 30b50d1 :) 

WRT the boilerplate stuff, yes I think it makes sense to ignore (or untrack?) some of those files.
How about:
* ABOUT-NLS
* config.rpath

Both of those were empty originally and are generated automatically, so they should be safe to ignore. Would that be ok?

**Comment by daf** [comment]
Basically it should be anything autoreconf installs for you, a partial list:

```
ABOUT-NLS
INSTALL
config.rpath
depcomp
install-sh
missing
po/Makefile*
po/Rules-quot
```

These are just the ones that are dirty in my working tree now - I'm sure there is more.

**Comment by JamesWrigley** [comment]
Ignored all those, and:
* configure
* compile
* Makefile
* Makefile.in
* po/Makevars.template
* po/*.sin
* po/\*quot\*
* data/nitrogen.desktop
* src/nitrogen (not generated by autoreconf, but I thought it was worth putting in)

**Pull request merged**
